In [40]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/customer-segmentation-tutorial-in-python/Mall_Customers.csv

In [41]:
df=pd.read_csv("/kaggle/input/customer-segmentation-tutorial-in-python/Mall_Customers.csv")

In [42]:
df.head()

   CustomerID  Gender  Age  Annual Income (k$)  Spending Score (1-100)
0           1    Male   19                  15                      39
1           2    Male   21                  15                      81
2           3  Female   20                  16                       6
3           4  Female   23                  16                      77
4           5  Female   31                  17                      40

In [43]:
df.isnull().sum()

CustomerID                0
Gender                    0
Age                       0
Annual Income (k$)        0
Spending Score (1-100)    0
dtype: int64

In [44]:
df.describe()

       CustomerID         Age  Annual Income (k$)  Spending Score (1-100)
count  200.000000  200.000000          200.000000              200.000000
mean   100.500000   38.850000           60.560000               50.200000
std     57.879185   13.969007           26.264721               25.823522
min      1.000000   18.000000           15.000000                1.000000
25%     50.750000   28.750000           41.500000               34.750000
50%    100.500000   36.000000           61.500000               50.000000
75%    150.250000   49.000000           78.000000               73.000000
max    200.000000   70.000000          137.000000               99.000000

In [45]:
df['Gender']=df['Gender'].fillna(df['Gender'].mode()[0])

In [46]:
df['Gender']

0        Male
1        Male
2      Female
3      Female
4      Female
        ...
195    Female
196    Female
197      Male
198      Male
199      Male
Name: Gender, Length: 200, dtype: object

In [47]:
from sklearn.preprocessing import StandardScaler

In [48]:
scaler= StandardScaler()

In [49]:
df[['Age', 'Annual Income (k$)', 'Spending Score (1-100)']]=scaler.fit_transform(df[['Age',	'Annual Income (k$)',	'Spending Score (1-100)']])

In [50]:
df.columns

Index(['CustomerID', 'Gender', 'Age', 'Annual Income (k$)',
       'Spending Score (1-100)'],
      dtype='object')

In [51]:
from sklearn.preprocessing import OneHotEncoder

In [52]:

enc = OneHotEncoder(drop='first', sparse_output=False)
gender_encoded = enc.fit_transform(df[['Gender']])
gender_df = pd.DataFrame(gender_encoded, columns=enc.get_feature_names_out(['Gender']))

In [53]:
X = pd.concat([df[['Age', 'Annual Income (k$)']], gender_df], axis=1)
y = df['Spending Score (1-100)']

In [54]:
from sklearn.model_selection import train_test_split

In [55]:
x_train,x_test,y_train,y_test=train_test_split(X,y)

In [56]:
# Sklearn models
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor


# XGBoost

from xgboost import XGBRegressor

In [57]:
models = {
    
     "Linear Regression": LinearRegression(),
    "Random Forest": RandomForestRegressor(random_state=42),
    
  "Xgb_model": XGBRegressor(random_state=42)


}

In [63]:
for model_name in models.keys():
    models[model_name].fit(x_train,y_train)
    print(model_name)
    print( models[model_name].score(x_test,y_test))
    print(models[model_name].predict(x_test))

Linear Regression
0.20782228073412057
[-0.21332443  0.26064504  0.35259379 -0.39592403  0.06418172 -0.48667186
  0.22342915  0.34205719 -0.03810037 -0.2155436  -0.04252213 -0.08600965
  0.26354306 -0.57865051  0.22748159  0.08659603 -0.33014909  0.24591983
  0.04284547  0.34427636 -0.42209784  0.03486746  0.14269585  0.35937089
  0.19476384  0.35858578 -0.22580057 -0.23432126  0.27829817 -0.152124
  0.43066223  0.00413572  0.21699147 -0.06163921 -0.63835708  0.15495945
  0.20305137  0.21429671 -0.22229081  0.08476275  0.2760491  -0.39997647
  0.34731054  0.14402364 -0.45215073 -0.58356444  0.13468794  0.2726456
 -0.57119456  0.23004019]
Random Forest
-0.030788157005220418
[-0.21973003  1.00276091  0.41383784 -1.26247715  0.34861762 -1.38398864
  0.00815253 -0.06366736 -1.24423102 -0.5198207  -0.55398367 -0.03105725
  0.04619766 -1.31294518  1.0286096   0.57688839  0.05939699 -0.06871416
  1.30556909 -0.38782739 -0.0248458   0.35405263  0.13548725  0.22671791
  1.48764221 -0.02212829 -1.22210273 -0.41616713  0.20847178 -0.2337058
 -0.08890137  0.91347132  0.15023944 -0.09006602 -1.31294518  1.08467441
  0.07531383  0.72958653 -1.35875462  1.12808985 -0.12034684 -0.05396197
  0.26088089  1.15494143 -0.06599665 -0.03299833  1.28182323 -0.20109568
 -0.05240911  0.95423396]
Xgb_model
-0.21079916923643238
[-2.45195389e-01  1.06714451e+00  7.35493720e-01 -1.29892588e+00
  5.75489283e-01 -1.71185112e+00 -3.13639134e-01 -1.58634007e-01
 -1.14892757e+00 -5.96989870e-01 -7.53488600e-01 -3.22081782e-02
 -8.75193104e-02 -1.15966499e+00  1.68106496e+00  6.72179461e-01
  7.62588307e-02 -1.23602465e-01  1.85841405e+00 -3.67886990e-01
 -4.63847555e-02  8.13457131e-01  1.02732725e-01  6.88423812e-01
  1.37277770e+00 -1.42573146e-03 -9.00311649e-01 -2.76662976e-01
 -3.79552469e-02 -3.83155346e-01 -8.56547058e-02  5.58488250e-01
  1.64777264e-01 -1.46128550e-01 -1.20485091e+00  7.04473138e-01
 -4.00706828e-02  3.72498930e-01 -1.57902992e+00  1.52434731e+00
 -5.08822262e-01 -1.43047243e-01  3.47254068e-01  1.78331721e+00
 -6.86912313e-02 -1.22560449e-01  1.32725918e+00  4.72387850e-01
 -1.77854881e-01  1.23102212e+00]

In [64]:
preds=models[model_name].predict(x_test)

In [65]:
preds

array([-2.45195389e-01,  1.06714451e+00,  7.35493720e-01, -1.29892588e+00,
        5.75489283e-01, -1.71185112e+00, -3.13639134e-01, -1.58634007e-01,
       -1.14892757e+00, -5.96989870e-01, -7.53488600e-01, -3.22081782e-02,
       -8.75193104e-02, -1.15966499e+00,  1.68106496e+00,  6.72179461e-01,
        7.62588307e-02, -1.23602465e-01,  1.85841405e+00, -3.67886990e-01,
       -4.63847555e-02,  8.13457131e-01,  1.02732725e-01,  6.88423812e-01,
        1.37277770e+00, -1.42573146e-03, -9.00311649e-01, -2.76662976e-01,
       -3.79552469e-02, -3.83155346e-01, -8.56547058e-02,  5.58488250e-01,
        1.64777264e-01, -1.46128550e-01, -1.20485091e+00,  7.04473138e-01,
       -4.00706828e-02,  3.72498930e-01, -1.57902992e+00,  1.52434731e+00,
       -5.08822262e-01, -1.43047243e-01,  3.47254068e-01,  1.78331721e+00,
       -6.86912313e-02, -1.22560449e-01,  1.32725918e+00,  4.72387850e-01,
       -1.77854881e-01,  1.23102212e+00], dtype=float32)

In [59]:
from sklearn.decomposition import PCA

In [60]:
PCA = PCA(n_components=2)
X_pca=PCA.fit_transform(df[['Age', 'Annual Income (k$)', 'Spending Score (1-100)']])

In [61]:
print("Shape of PCA data:", X_pca.shape)

Shape of PCA data: (200, 2)

In [75]:
df_submission = pd.DataFrame()
df_submission['CustomerID'] = df['CustomerID']       
df_submission['Spending Score (1-100)'] = models[model_name].predict(X)


df_submission.to_csv("finalpre.csv", index=False)
print("Submission file saved as final.csv")

Submission file saved as final.csv